config/routes.rb
Rails.application.routes.draw do
  root "homepage#show"

  resources :blog_posts
  get "/blog", to: "blog_posts#index", as: 'blog'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	belongs_to :user
	has_many :comments

	validates :title, presence: { message: "Must include a title" }, 
						length: { minimum: 5 }

	validates :content, presence: { message: "Must include content" }, 
						length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog_post
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :blog_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
	def index
		@blogs = BlogPost.all
	end

	def new 
		@post = BlogPost.new
	end

	def show
		@post = BlogPost.find(params[:id])
	end

	def create
		@post = BlogPost.new(blog_params)
		if @post.save
			flash[:success] = "Post was successfully published."
			redirect_to @post
		else
			render 'new'
		end
	end

	def destroy
		@post = BlogPost.find(params[:id])
		@post.destroy
	end

	private

	def blog_params
		params[:blog_post].permit(:title, :content)
	end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	def show
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/blog_posts/index.html.erb
<%= render 'partials/header' %>

<%= render 'partials/blog_nav' %>

<%= render 'partials/blog' %>

<%= render 'partials/footer' %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<div class="new-blog-form">

	<%= form_for(@post) do |form| %>
		<% if @post.errors.any? %>
	    <div id="error_explanation">
	    	<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

	      	<ul>
	      		<% @post.errors.full_messages.each do |msg| %>
	        		<li><%= msg %></li>
	      		<% end %>
	      	</ul>
	    </div>
		<% end %>  

		<%= form.label :title %><br>
		<%= form.text_field :title %><br>

		<%= form.label :content %><br>
		<%= form.text_area :content %><br>

		<%= form.submit "Publish" %> 
	<% end %>

</div>

app/views/blog_posts/show.html.erb
<%= render 'partials/header' %>

<%= render 'partials/blog_nav' %>



<section id="blog-section">
	<div class="container">
		<div class="white-wrapper">
				<article class="blog-post-<%= @post.id %>">
					<h2><%= @post.title.titleize %></h2>
					<h4>By: <%= @post.author %></h4>
					<p class="date">Date: <%= @post.created_at %></p>
					<p><%= @post.content %></p>
				</article>
				<hr>
				<%= link_to "Back to Blog", blog_posts_path %>
				<div class="comments">
					<h3>Comments: 
						<% if @post.comments.count > 0 %>
							<%= @post.comments.count %>
						<% else %>
							<%= "0" %>
						<% end %>
					</h3>

					<% @post.comments.all.each do |comment| %>
						<div class="comment-<%= comment.id %>">
							<div class="comment-info">
								<span>
									<%= "#{comment.first_name} #{comment.last_name}" %>
								</span>
							</div>
							<p><%= comment.content %></p>
							<hr>
						</div>
					<% end %>
				</div>
		</div>

		<aside>
			<h2>About me</h2>
			<figure class="blog-photo">
				<%= image_tag("chris.jpg", alt: "Photo of Chris Dziewa") %>
			</figure>	
			<p>Hey, I'm Chris Dziewa and welcome to my blog. This is where I write about my journey to teach myself web development.</p>
		</aside>
	</div>
</section>

app/views/homepage/show.html.erb
	<%= render 'partials/header' %>

	<%= render 'partials/nav' %>

	<%= render 'partials/hero' %>

	<%= render 'partials/about' %>

	<%= render 'partials/work' %>

	<%= render 'partials/contact' %>

	<%= render 'partials/footer' %>

	<script type="text/javascript" charset="utf-8">
		$(window).ready(function() {
		$('.flexslider').flexslider();
		});
	</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chris Dziewa | Web Developer</title>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Poiret+One' %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Kameron' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |type, message| %>
    	<div class="<%= type %>">
    		<%= message %>
    	</div>
  <% end %>		
<%= yield %>

</body>
</html>

app/views/partials/_about.html.erb
<section id="about">
	<div class="container">
		<h1>About</h1>

		<div class="about-photo-contain">
			<figure class="about-photo">
				<%= image_tag("chris-bw.png", alt: "photo of Chris Dziewa") %>
			</figure>
		</div>

		<p>My name is Chris Dziewa and welcome to my portfolio! I have spent over a 2 years teaching myself to program and just can't get enough. My hope is to one day be a full-time developer making awesome things.</p> 
		<br>
		<p>
			Although I have gained knowledge about a vast amount of technologies, my favorites include jQuery, Ruby and Python. If you need help on your next project or you are looking for a hard-working employee you can count on, then please don't hesitate to contact me! Thank you for stopping by my page!
		</p>

		<a href="#" class="arrow-to-top"> </a>
	</div>
</section>

app/views/partials/_blog.html.erb
<section id="blog-section">
	<div class="container">
		<div class="white-wrapper">
			<% @blogs.all.each do |post| %>
				<article class="blog-post-<%= post.id %>">
					<h2><%= link_to post.title.titleize, blog_post_path(post) %></h2>
					<h4>By: <%= post.author %></h4>
					<p class="date">Date: <%= post.created_at %></p>
					<p><%= post.content %></p>
				</article>
				<hr>
			<% end %>
		</div>

		<aside>
			<h2>About me</h2>
			<figure class="blog-photo">
				<%= image_tag("chris.jpg", alt: "Photo of Chris Dziewa") %>
			</figure>	
			<p>Hey, I'm Chris Dziewa and welcome to my blog. This is where I write about my journey to teach myself web development.</p>
		</aside>
	</div>
</section>

app/views/partials/_blog_nav.html.erb
	<nav>
		<div class="container">
			<%= link_to "Home", root_path, class: "home-link" %>
			
			<%= link_to "Blog", blog_path %>
		</div>
	</nav>

app/views/partials/_contact.html.erb
<section id="contact">
	<div class="container">
		<h1>Contact</h1>
	
		<form novalidate>
			<label for="name">Name</label> <br>
			<input id="name"><br>

			<label for="email">Email</label><br>
			<input type="email" id="email"><br>

			<label for="message">Message</label><br>
			<textarea id="message"></textarea><br>

			<input type="submit" value="Send">
		</form>

		<div class="contact-info">
			<p>Email: <span>chris.dziewa@gmail.com</span></p>
			<p>Phone: <span>952-977-8485</span></p>
		</div>
	</div>
</section>

app/views/partials/_footer.html.erb
<footer>
	<div class="container">
		
		<p>&copy;2014 Chris Dziewa</p>
	</div>	
	
</footer>

app/views/partials/_header.html.erb
	<header id="top" class="header-scrolled">
		<div class="container">
			<h1>Chris Dziewa</h1>
			<h4>Web Developer</h4>
		</div>
	</header>

app/views/partials/_hero.html.erb
<section id="hero">
	<div class="container">
		<h2>Elegant designs<br>for your brand</h2>
	
		<%= image_tag("arrow.png", alt: "arrow made of bubbles", class: "scroll-arrow") %>
	</div>
</section>

app/views/partials/_nav.html.erb
	<nav>
		<div class="container"><a  href="#about">About</a>
			<a  href="#work">Work</a>
			<%= link_to "Blog", blog_path %>
			<a  href="#contact">Contact</a>
		</div>
	</nav>

app/views/partials/_work.html.erb
<section id="work">
	<div class="container">
		<h1>Work</h1>

		<div class="flexslider">
			<ul class="slides">
				<li>
					<div class="content">
						<%= image_tag("stafford-site.png", alt: "screenshot of stafford-photo.com" ) %>	
						<h2>www.stafford-photo.com</h2>
						
						<p>Photography portfolio site for photographer Alex Stafford. Alex is a local Milwaukee-area photographer specializing in portrait, engagement and wedding photography.This site was designed and handcoded as a fully-editable custom WordPress theme. </p>

						<a class="site-button" href="http://www.stafford-photo.com">Go to site</a>
					</div>
				</li>


				<li>
					<div class="content">

						<%= image_tag("lcp-site.png", alt: "screenshot of lakecountryplumbing.com" ) %>
						
						<h2>www.lakecountryplumbing.com</h2>
						
						<p>Plumbing business site for Brian Hohnke of Lake Country Plumbing Co. Lake Country Plumbing Co. is a family-run business offering plumbing, maintenance and remodeling services in Southeastern Wisconsin. Site was developed using handcoded PHP.</p>

						<a class="site-button" href="http://www.lakecountryplumbing.com">Go to site</a>
					</div>
				</li>
			</ul>
		</div>
	</div>
</section>